# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Draf#1_QT1.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QFrame, QGroupBox, QLabel, QLineEdit,
    QPushButton, QScrollArea, QSizePolicy, QStackedWidget,
    QTextBrowser, QVBoxLayout, QWidget)

from pyqtgraph import PlotWidget

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1016, 756)
        self.board_frame = QFrame(Dialog)
        self.board_frame.setObjectName(u"board_frame")
        self.board_frame.setGeometry(QRect(0, 0, 1001, 111))
        self.board_frame.setStyleSheet(u"")
        self.board_frame.setFrameShape(QFrame.StyledPanel)
        self.board_frame.setFrameShadow(QFrame.Raised)
        self.Connect_board_groupBox = QGroupBox(self.board_frame)
        self.Connect_board_groupBox.setObjectName(u"Connect_board_groupBox")
        self.Connect_board_groupBox.setGeometry(QRect(0, 10, 491, 91))
        self.Connect_board_groupBox.setStyleSheet(u"")
        self.board_host_name_label = QLabel(self.Connect_board_groupBox)
        self.board_host_name_label.setObjectName(u"board_host_name_label")
        self.board_host_name_label.setGeometry(QRect(10, 20, 71, 20))
        self.host_name_comboBox = QComboBox(self.Connect_board_groupBox)
        self.host_name_comboBox.addItem("")
        self.host_name_comboBox.addItem("")
        # self.host_name_comboBox.addItem("")
        self.host_name_comboBox.setObjectName(u"host_name_comboBox")
        self.host_name_comboBox.setGeometry(QRect(90, 20, 151, 22))
        self.connect_pushButton = QPushButton(self.Connect_board_groupBox)
        self.connect_pushButton.setObjectName(u"connect_pushButton")
        self.connect_pushButton.setGeometry(QRect(260, 20, 61, 21))
        self.status_board_label = QLabel(self.Connect_board_groupBox)
        self.status_board_label.setObjectName(u"status_board_label")
        self.status_board_label.setGeometry(QRect(260, 50, 111, 16))
        self.disconnect_pushButton = QPushButton(self.Connect_board_groupBox)
        self.disconnect_pushButton.setObjectName(u"disconnect_pushButton")
        self.disconnect_pushButton.setGeometry(QRect(330, 20, 71, 21))
        self.poweroff_pushButton = QPushButton(self.Connect_board_groupBox)
        self.poweroff_pushButton.setObjectName(u"poweroff_pushButton")
        self.poweroff_pushButton.setGeometry(QRect(410, 20, 71, 21))
        self.run_pushButton = QPushButton(self.board_frame)
        self.run_pushButton.setObjectName(u"run_pushButton")
        self.run_pushButton.setGeometry(QRect(710, 80, 75, 24))
        self.run_pushButton.setStyleSheet(u"")
        self.stop_pushButton = QPushButton(self.board_frame)
        self.stop_pushButton.setObjectName(u"stop_pushButton")
        self.stop_pushButton.setGeometry(QRect(800, 80, 101, 24))
        self.stop_pushButton.setStyleSheet(u"")
        self.reset_pushButton = QPushButton(self.board_frame)
        self.reset_pushButton.setObjectName(u"reset_pushButton")
        self.reset_pushButton.setGeometry(QRect(920, 80, 75, 24))
        self.reset_pushButton.setStyleSheet(u"")
        self.selec_pin_frame = QFrame(Dialog)
        self.selec_pin_frame.setObjectName(u"selec_pin_frame")
        self.selec_pin_frame.setGeometry(QRect(9, 120, 141, 621))
        self.selec_pin_frame.setFrameShape(QFrame.StyledPanel)
        self.selec_pin_frame.setFrameShadow(QFrame.Raised)
        self.analog_pin_groupBox = QGroupBox(self.selec_pin_frame)
        self.analog_pin_groupBox.setObjectName(u"analog_pin_groupBox")
        self.analog_pin_groupBox.setGeometry(QRect(10, 29, 121, 141))
        self.analog_pin_scrollArea = QScrollArea(self.analog_pin_groupBox)
        self.analog_pin_scrollArea.setObjectName(u"analog_pin_scrollArea")
        self.analog_pin_scrollArea.setGeometry(QRect(0, 19, 121, 121))
        self.analog_pin_scrollArea.setWidgetResizable(True)
        self.analog_pin_scrollAreaWidgetContents = QWidget()
        self.analog_pin_scrollAreaWidgetContents.setObjectName(u"analog_pin_scrollAreaWidgetContents")
        self.analog_pin_scrollAreaWidgetContents.setGeometry(QRect(0, 0, 119, 119))
        self.verticalLayout_2 = QVBoxLayout(self.analog_pin_scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.AOUT_0_checkBox = QCheckBox(self.analog_pin_scrollAreaWidgetContents)
        self.AOUT_0_checkBox.setObjectName(u"AOUT_0_checkBox")

        self.verticalLayout_2.addWidget(self.AOUT_0_checkBox)

        self.AOUT_1_checkBox = QCheckBox(self.analog_pin_scrollAreaWidgetContents)
        self.AOUT_1_checkBox.setObjectName(u"AOUT_1_checkBox")

        self.verticalLayout_2.addWidget(self.AOUT_1_checkBox)

        self.AOUT_2_checkBox = QCheckBox(self.analog_pin_scrollAreaWidgetContents)
        self.AOUT_2_checkBox.setObjectName(u"AOUT_2_checkBox")

        self.verticalLayout_2.addWidget(self.AOUT_2_checkBox)

        self.AOUT_3_checkBox = QCheckBox(self.analog_pin_scrollAreaWidgetContents)
        self.AOUT_3_checkBox.setObjectName(u"AOUT_3_checkBox")

        self.verticalLayout_2.addWidget(self.AOUT_3_checkBox)

        self.analog_pin_scrollArea.setWidget(self.analog_pin_scrollAreaWidgetContents)
        self.digital_pin_groupBox = QGroupBox(self.selec_pin_frame)
        self.digital_pin_groupBox.setObjectName(u"digital_pin_groupBox")
        self.digital_pin_groupBox.setGeometry(QRect(10, 210, 121, 401))
        self.digital_pin_scrollArea = QScrollArea(self.digital_pin_groupBox)
        self.digital_pin_scrollArea.setObjectName(u"digital_pin_scrollArea")
        self.digital_pin_scrollArea.setGeometry(QRect(0, 20, 121, 381))
        self.digital_pin_scrollArea.setWidgetResizable(True)
        self.digital_pin_scrollAreaWidgetContents = QWidget()
        self.digital_pin_scrollAreaWidgetContents.setObjectName(u"digital_pin_scrollAreaWidgetContents")
        self.digital_pin_scrollAreaWidgetContents.setGeometry(QRect(0, 0, 102, 584))
        self.verticalLayout = QVBoxLayout(self.digital_pin_scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.D_0_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_0_N_checkBox.setObjectName(u"D_0_N_checkBox")

        self.verticalLayout.addWidget(self.D_0_N_checkBox)

        self.D_1_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_1_N_checkBox.setObjectName(u"D_1_N_checkBox")

        self.verticalLayout.addWidget(self.D_1_N_checkBox)

        self.D_2_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_2_N_checkBox.setObjectName(u"D_2_N_checkBox")

        self.verticalLayout.addWidget(self.D_2_N_checkBox)

        self.D_3_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_3_N_checkBox.setObjectName(u"D_3_N_checkBox")

        self.verticalLayout.addWidget(self.D_3_N_checkBox)

        self.D_4_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_4_N_checkBox.setObjectName(u"D_4_N_checkBox")

        self.verticalLayout.addWidget(self.D_4_N_checkBox)

        self.D_5_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_5_N_checkBox.setObjectName(u"D_5_N_checkBox")

        self.verticalLayout.addWidget(self.D_5_N_checkBox)

        self.D_6_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_6_N_checkBox.setObjectName(u"D_6_N_checkBox")

        self.verticalLayout.addWidget(self.D_6_N_checkBox)

        self.D_7_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_7_N_checkBox.setObjectName(u"D_7_N_checkBox")

        self.verticalLayout.addWidget(self.D_7_N_checkBox)

        self.D_8_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_8_N_checkBox.setObjectName(u"D_8_N_checkBox")

        self.verticalLayout.addWidget(self.D_8_N_checkBox)

        self.D_9_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_9_N_checkBox.setObjectName(u"D_9_N_checkBox")

        self.verticalLayout.addWidget(self.D_9_N_checkBox)

        self.D_10_N_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_10_N_checkBox.setObjectName(u"D_10_N_checkBox")

        self.verticalLayout.addWidget(self.D_10_N_checkBox)

        self.D_0_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_0_P_checkBox.setObjectName(u"D_0_P_checkBox")

        self.verticalLayout.addWidget(self.D_0_P_checkBox)

        self.D_1_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_1_P_checkBox.setObjectName(u"D_1_P_checkBox")

        self.verticalLayout.addWidget(self.D_1_P_checkBox)

        self.D_2_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_2_P_checkBox.setObjectName(u"D_2_P_checkBox")

        self.verticalLayout.addWidget(self.D_2_P_checkBox)

        self.D_3_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_3_P_checkBox.setObjectName(u"D_3_P_checkBox")

        self.verticalLayout.addWidget(self.D_3_P_checkBox)

        self.D_4_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_4_P_checkBox.setObjectName(u"D_4_P_checkBox")

        self.verticalLayout.addWidget(self.D_4_P_checkBox)

        self.D_5_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_5_P_checkBox.setObjectName(u"D_5_P_checkBox")

        self.verticalLayout.addWidget(self.D_5_P_checkBox)

        self.D_6_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_6_P_checkBox.setObjectName(u"D_6_P_checkBox")

        self.verticalLayout.addWidget(self.D_6_P_checkBox)

        self.D_7_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_7_P_checkBox.setObjectName(u"D_7_P_checkBox")

        self.verticalLayout.addWidget(self.D_7_P_checkBox)

        self.D_8_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_8_P_checkBox.setObjectName(u"D_8_P_checkBox")

        self.verticalLayout.addWidget(self.D_8_P_checkBox)

        self.D_9_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_9_P_checkBox.setObjectName(u"D_9_P_checkBox")

        self.verticalLayout.addWidget(self.D_9_P_checkBox)

        self.D_10_P_checkBox = QCheckBox(self.digital_pin_scrollAreaWidgetContents)
        self.D_10_P_checkBox.setObjectName(u"D_10_P_checkBox")

        self.verticalLayout.addWidget(self.D_10_P_checkBox)

        self.digital_pin_scrollArea.setWidget(self.digital_pin_scrollAreaWidgetContents)
        self.Add_Digital_Signal_pushButton = QPushButton(self.selec_pin_frame)
        self.Add_Digital_Signal_pushButton.setObjectName(u"Add_Digital_Signal_pushButton")
        self.Add_Digital_Signal_pushButton.setEnabled(False)
        self.Add_Digital_Signal_pushButton.setGeometry(QRect(10, 180, 121, 24))
        self.Add_Analog_Signal_pushButton = QPushButton(self.selec_pin_frame)
        self.Add_Analog_Signal_pushButton.setObjectName(u"Add_Analog_Signal_pushButton")
        self.Add_Analog_Signal_pushButton.setEnabled(False)
        self.Add_Analog_Signal_pushButton.setGeometry(QRect(10, 0, 121, 24))
        self.set_pin_and_show_graph = QFrame(Dialog)
        self.set_pin_and_show_graph.setObjectName(u"set_pin_and_show_graph")
        self.set_pin_and_show_graph.setGeometry(QRect(160, 120, 601, 491))
        self.set_pin_and_show_graph.setFrameShape(QFrame.StyledPanel)
        self.set_pin_and_show_graph.setFrameShadow(QFrame.Raised)
        self.set_pin_and_show_scrollArea = QScrollArea(self.set_pin_and_show_graph)
        self.set_pin_and_show_scrollArea.setObjectName(u"set_pin_and_show_scrollArea")
        self.set_pin_and_show_scrollArea.setGeometry(QRect(0, 0, 601, 471))
        self.set_pin_and_show_scrollArea.setWidgetResizable(True)
        self.set_pin_and_show_scrollAreaWidgetContents = QWidget()
        self.set_pin_and_show_scrollAreaWidgetContents.setObjectName(u"set_pin_and_show_scrollAreaWidgetContents")
        self.set_pin_and_show_scrollAreaWidgetContents.setGeometry(QRect(0, 0, 582, 2294))
        self.verticalLayout_3 = QVBoxLayout(self.set_pin_and_show_scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.set_pin_and_show_frame = QFrame(self.set_pin_and_show_scrollAreaWidgetContents)
        self.set_pin_and_show_frame.setObjectName(u"set_pin_and_show_frame")
        self.set_pin_and_show_frame.setFrameShape(QFrame.StyledPanel)
        self.set_pin_and_show_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.set_pin_and_show_frame)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.set_pin_and_show_aout0_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_aout0_groupBox.setObjectName(u"set_pin_and_show_aout0_groupBox")
        self.set_pin_and_show_aout0_groupBox.setMinimumSize(QSize(541, 81))
        self.AOUT_0_show_widget = PlotWidget(self.set_pin_and_show_aout0_groupBox)
        self.AOUT_0_show_widget.setObjectName(u"AOUT_0_show_widget")
        self.AOUT_0_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.AOUT_0_show_widget.setToolTipDuration(1)
        self.AOUT_0_pushButton = QPushButton(self.set_pin_and_show_aout0_groupBox)
        self.AOUT_0_pushButton.setObjectName(u"AOUT_0_pushButton")
        self.AOUT_0_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_aout0_groupBox)

        self.set_pin_and_show_aout1_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_aout1_groupBox.setObjectName(u"set_pin_and_show_aout1_groupBox")
        self.set_pin_and_show_aout1_groupBox.setMinimumSize(QSize(541, 81))
        self.AOUT_1_show_widget = PlotWidget(self.set_pin_and_show_aout1_groupBox)
        self.AOUT_1_show_widget.setObjectName(u"AOUT_1_show_widget")
        self.AOUT_1_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.AOUT_1_pushButton = QPushButton(self.set_pin_and_show_aout1_groupBox)
        self.AOUT_1_pushButton.setObjectName(u"AOUT_1_pushButton")
        self.AOUT_1_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_aout1_groupBox)

        self.set_pin_and_show_aout2_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_aout2_groupBox.setObjectName(u"set_pin_and_show_aout2_groupBox")
        self.set_pin_and_show_aout2_groupBox.setMinimumSize(QSize(541, 81))
        self.AOUT_2_show_widget = PlotWidget(self.set_pin_and_show_aout2_groupBox)
        self.AOUT_2_show_widget.setObjectName(u"AOUT_2_show_widget")
        self.AOUT_2_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.AOUT_2_pushButton = QPushButton(self.set_pin_and_show_aout2_groupBox)
        self.AOUT_2_pushButton.setObjectName(u"AOUT_2_pushButton")
        self.AOUT_2_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_aout2_groupBox)

        self.set_pin_and_show_aout3_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_aout3_groupBox.setObjectName(u"set_pin_and_show_aout3_groupBox")
        self.set_pin_and_show_aout3_groupBox.setMinimumSize(QSize(541, 81))
        self.AOUT_3_show_widget = PlotWidget(self.set_pin_and_show_aout3_groupBox)
        self.AOUT_3_show_widget.setObjectName(u"AOUT_3_show_widget")
        self.AOUT_3_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.AOUT_3_pushButton = QPushButton(self.set_pin_and_show_aout3_groupBox)
        self.AOUT_3_pushButton.setObjectName(u"AOUT_3_pushButton")
        self.AOUT_3_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_aout3_groupBox)

        self.set_pin_and_show_D_0_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_0_N_groupBox.setObjectName(u"set_pin_and_show_D_0_N_groupBox")
        self.set_pin_and_show_D_0_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_0_N_show_widget = PlotWidget(self.set_pin_and_show_D_0_N_groupBox)
        self.D_0_N_show_widget.setObjectName(u"D_0_N_show_widget")
        self.D_0_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_0_N_pushButton = QPushButton(self.set_pin_and_show_D_0_N_groupBox)
        self.D_0_N_pushButton.setObjectName(u"D_0_N_pushButton")
        self.D_0_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_0_N_groupBox)

        self.set_pin_and_show_D_1_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_1_N_groupBox.setObjectName(u"set_pin_and_show_D_1_N_groupBox")
        self.set_pin_and_show_D_1_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_1_N_show_widget = PlotWidget(self.set_pin_and_show_D_1_N_groupBox)
        self.D_1_N_show_widget.setObjectName(u"D_1_N_show_widget")
        self.D_1_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_1_N_pushButton = QPushButton(self.set_pin_and_show_D_1_N_groupBox)
        self.D_1_N_pushButton.setObjectName(u"D_1_N_pushButton")
        self.D_1_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_1_N_groupBox)

        self.set_pin_and_show_D_2_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_2_N_groupBox.setObjectName(u"set_pin_and_show_D_2_N_groupBox")
        self.set_pin_and_show_D_2_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_2_N_show_widget = PlotWidget(self.set_pin_and_show_D_2_N_groupBox)
        self.D_2_N_show_widget.setObjectName(u"D_2_N_show_widget")
        self.D_2_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_2_N_pushButton = QPushButton(self.set_pin_and_show_D_2_N_groupBox)
        self.D_2_N_pushButton.setObjectName(u"D_2_N_pushButton")
        self.D_2_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_2_N_groupBox)

        self.set_pin_and_show_D_3_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_3_N_groupBox.setObjectName(u"set_pin_and_show_D_3_N_groupBox")
        self.set_pin_and_show_D_3_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_3_N_show_widget = PlotWidget(self.set_pin_and_show_D_3_N_groupBox)
        self.D_3_N_show_widget.setObjectName(u"D_3_N_show_widget")
        self.D_3_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_3_N_pushButton = QPushButton(self.set_pin_and_show_D_3_N_groupBox)
        self.D_3_N_pushButton.setObjectName(u"D_3_N_pushButton")
        self.D_3_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_3_N_groupBox)

        self.set_pin_and_show_D_4_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_4_N_groupBox.setObjectName(u"set_pin_and_show_D_4_N_groupBox")
        self.set_pin_and_show_D_4_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_4_N_show_widget = PlotWidget(self.set_pin_and_show_D_4_N_groupBox)
        self.D_4_N_show_widget.setObjectName(u"D_4_N_show_widget")
        self.D_4_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_4_N_pushButton = QPushButton(self.set_pin_and_show_D_4_N_groupBox)
        self.D_4_N_pushButton.setObjectName(u"D_4_N_pushButton")
        self.D_4_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_4_N_groupBox)

        self.set_pin_and_show_D_5_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_5_N_groupBox.setObjectName(u"set_pin_and_show_D_5_N_groupBox")
        self.set_pin_and_show_D_5_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_5_N_show_widget = PlotWidget(self.set_pin_and_show_D_5_N_groupBox)
        self.D_5_N_show_widget.setObjectName(u"D_5_N_show_widget")
        self.D_5_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_5_N_pushButton = QPushButton(self.set_pin_and_show_D_5_N_groupBox)
        self.D_5_N_pushButton.setObjectName(u"D_5_N_pushButton")
        self.D_5_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_5_N_groupBox)

        self.set_pin_and_show_D_6_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_6_N_groupBox.setObjectName(u"set_pin_and_show_D_6_N_groupBox")
        self.set_pin_and_show_D_6_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_6_N_show_widget = PlotWidget(self.set_pin_and_show_D_6_N_groupBox)
        self.D_6_N_show_widget.setObjectName(u"D_6_N_show_widget")
        self.D_6_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_6_N_pushButton = QPushButton(self.set_pin_and_show_D_6_N_groupBox)
        self.D_6_N_pushButton.setObjectName(u"D_6_N_pushButton")
        self.D_6_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_6_N_groupBox)

        self.set_pin_and_show_D_7_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_7_N_groupBox.setObjectName(u"set_pin_and_show_D_7_N_groupBox")
        self.set_pin_and_show_D_7_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_7_N_show_widget = PlotWidget(self.set_pin_and_show_D_7_N_groupBox)
        self.D_7_N_show_widget.setObjectName(u"D_7_N_show_widget")
        self.D_7_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_7_N_pushButton = QPushButton(self.set_pin_and_show_D_7_N_groupBox)
        self.D_7_N_pushButton.setObjectName(u"D_7_N_pushButton")
        self.D_7_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_7_N_groupBox)

        self.set_pin_and_show_D_8_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_8_N_groupBox.setObjectName(u"set_pin_and_show_D_8_N_groupBox")
        self.set_pin_and_show_D_8_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_8_N_show_widget = PlotWidget(self.set_pin_and_show_D_8_N_groupBox)
        self.D_8_N_show_widget.setObjectName(u"D_8_N_show_widget")
        self.D_8_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_8_N_pushButton = QPushButton(self.set_pin_and_show_D_8_N_groupBox)
        self.D_8_N_pushButton.setObjectName(u"D_8_N_pushButton")
        self.D_8_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_8_N_groupBox)

        self.set_pin_and_show_D_9_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_9_N_groupBox.setObjectName(u"set_pin_and_show_D_9_N_groupBox")
        self.set_pin_and_show_D_9_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_9_N_show_widget = PlotWidget(self.set_pin_and_show_D_9_N_groupBox)
        self.D_9_N_show_widget.setObjectName(u"D_9_N_show_widget")
        self.D_9_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_9_N_pushButton = QPushButton(self.set_pin_and_show_D_9_N_groupBox)
        self.D_9_N_pushButton.setObjectName(u"D_9_N_pushButton")
        self.D_9_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_9_N_groupBox)

        self.set_pin_and_show_D_10_N_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_10_N_groupBox.setObjectName(u"set_pin_and_show_D_10_N_groupBox")
        self.set_pin_and_show_D_10_N_groupBox.setMinimumSize(QSize(541, 81))
        self.D_10_N_show_widget = PlotWidget(self.set_pin_and_show_D_10_N_groupBox)
        self.D_10_N_show_widget.setObjectName(u"D_10_N_show_widget")
        self.D_10_N_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_10_N_pushButton = QPushButton(self.set_pin_and_show_D_10_N_groupBox)
        self.D_10_N_pushButton.setObjectName(u"D_10_N_pushButton")
        self.D_10_N_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_10_N_groupBox)

        self.set_pin_and_show_D_0_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_0_P_groupBox.setObjectName(u"set_pin_and_show_D_0_P_groupBox")
        self.set_pin_and_show_D_0_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_0_P_show_widget = PlotWidget(self.set_pin_and_show_D_0_P_groupBox)
        self.D_0_P_show_widget.setObjectName(u"D_0_P_show_widget")
        self.D_0_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_0_P_pushButton = QPushButton(self.set_pin_and_show_D_0_P_groupBox)
        self.D_0_P_pushButton.setObjectName(u"D_0_P_pushButton")
        self.D_0_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_0_P_groupBox)

        self.set_pin_and_show_D_1_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_1_P_groupBox.setObjectName(u"set_pin_and_show_D_1_P_groupBox")
        self.set_pin_and_show_D_1_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_1_P_show_widget = PlotWidget(self.set_pin_and_show_D_1_P_groupBox)
        self.D_1_P_show_widget.setObjectName(u"D_1_P_show_widget")
        self.D_1_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_1_P_pushButton = QPushButton(self.set_pin_and_show_D_1_P_groupBox)
        self.D_1_P_pushButton.setObjectName(u"D_1_P_pushButton")
        self.D_1_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_1_P_groupBox)

        self.set_pin_and_show_D_2_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_2_P_groupBox.setObjectName(u"set_pin_and_show_D_2_P_groupBox")
        self.set_pin_and_show_D_2_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_2_P_show_widget = PlotWidget(self.set_pin_and_show_D_2_P_groupBox)
        self.D_2_P_show_widget.setObjectName(u"D_2_P_show_widget")
        self.D_2_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_2_P_pushButton = QPushButton(self.set_pin_and_show_D_2_P_groupBox)
        self.D_2_P_pushButton.setObjectName(u"D_2_P_pushButton")
        self.D_2_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_2_P_groupBox)

        self.set_pin_and_show_D_3_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_3_P_groupBox.setObjectName(u"set_pin_and_show_D_3_P_groupBox")
        self.set_pin_and_show_D_3_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_3_P_show_widget = PlotWidget(self.set_pin_and_show_D_3_P_groupBox)
        self.D_3_P_show_widget.setObjectName(u"D_3_P_show_widget")
        self.D_3_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_3_P_pushButton = QPushButton(self.set_pin_and_show_D_3_P_groupBox)
        self.D_3_P_pushButton.setObjectName(u"D_3_P_pushButton")
        self.D_3_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_3_P_groupBox)

        self.set_pin_and_show_D_4_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_4_P_groupBox.setObjectName(u"set_pin_and_show_D_4_P_groupBox")
        self.set_pin_and_show_D_4_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_4_P_show_widget = PlotWidget(self.set_pin_and_show_D_4_P_groupBox)
        self.D_4_P_show_widget.setObjectName(u"D_4_P_show_widget")
        self.D_4_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_4_P_pushButton = QPushButton(self.set_pin_and_show_D_4_P_groupBox)
        self.D_4_P_pushButton.setObjectName(u"D_4_P_pushButton")
        self.D_4_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_4_P_groupBox)

        self.set_pin_and_show_D_5_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_5_P_groupBox.setObjectName(u"set_pin_and_show_D_5_P_groupBox")
        self.set_pin_and_show_D_5_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_5_P_show_widget = PlotWidget(self.set_pin_and_show_D_5_P_groupBox)
        self.D_5_P_show_widget.setObjectName(u"D_5_P_show_widget")
        self.D_5_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_5_P_pushButton = QPushButton(self.set_pin_and_show_D_5_P_groupBox)
        self.D_5_P_pushButton.setObjectName(u"D_5_P_pushButton")
        self.D_5_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_5_P_groupBox)

        self.set_pin_and_show_D_6_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_6_P_groupBox.setObjectName(u"set_pin_and_show_D_6_P_groupBox")
        self.set_pin_and_show_D_6_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_6_P_show_widget = PlotWidget(self.set_pin_and_show_D_6_P_groupBox)
        self.D_6_P_show_widget.setObjectName(u"D_6_P_show_widget")
        self.D_6_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_6_P_pushButton = QPushButton(self.set_pin_and_show_D_6_P_groupBox)
        self.D_6_P_pushButton.setObjectName(u"D_6_P_pushButton")
        self.D_6_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_6_P_groupBox)

        self.set_pin_and_show_D_7_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_7_P_groupBox.setObjectName(u"set_pin_and_show_D_7_P_groupBox")
        self.set_pin_and_show_D_7_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_7_P_show_widget = PlotWidget(self.set_pin_and_show_D_7_P_groupBox)
        self.D_7_P_show_widget.setObjectName(u"D_7_P_show_widget")
        self.D_7_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_7_P_pushButton = QPushButton(self.set_pin_and_show_D_7_P_groupBox)
        self.D_7_P_pushButton.setObjectName(u"D_7_P_pushButton")
        self.D_7_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_7_P_groupBox)

        self.set_pin_and_show_D_8_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_8_P_groupBox.setObjectName(u"set_pin_and_show_D_8_P_groupBox")
        self.set_pin_and_show_D_8_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_8_P_show_widget = PlotWidget(self.set_pin_and_show_D_8_P_groupBox)
        self.D_8_P_show_widget.setObjectName(u"D_8_P_show_widget")
        self.D_8_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_8_P_pushButton = QPushButton(self.set_pin_and_show_D_8_P_groupBox)
        self.D_8_P_pushButton.setObjectName(u"D_8_P_pushButton")
        self.D_8_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_8_P_groupBox)

        self.set_pin_and_show_D_9_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_9_P_groupBox.setObjectName(u"set_pin_and_show_D_9_P_groupBox")
        self.set_pin_and_show_D_9_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_9_P_show_widget = PlotWidget(self.set_pin_and_show_D_9_P_groupBox)
        self.D_9_P_show_widget.setObjectName(u"D_9_P_show_widget")
        self.D_9_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_9_P_pushButton = QPushButton(self.set_pin_and_show_D_9_P_groupBox)
        self.D_9_P_pushButton.setObjectName(u"D_9_P_pushButton")
        self.D_9_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_9_P_groupBox)

        self.set_pin_and_show_D_10_P_groupBox = QGroupBox(self.set_pin_and_show_frame)
        self.set_pin_and_show_D_10_P_groupBox.setObjectName(u"set_pin_and_show_D_10_P_groupBox")
        self.set_pin_and_show_D_10_P_groupBox.setMinimumSize(QSize(541, 81))
        self.D_10_P_show_widget = PlotWidget(self.set_pin_and_show_D_10_P_groupBox)
        self.D_10_P_show_widget.setObjectName(u"D_10_P_show_widget")
        self.D_10_P_show_widget.setGeometry(QRect(139, 0, 401, 80))
        self.D_10_P_pushButton = QPushButton(self.set_pin_and_show_D_10_P_groupBox)
        self.D_10_P_pushButton.setObjectName(u"D_10_P_pushButton")
        self.D_10_P_pushButton.setGeometry(QRect(0, 0, 131, 81))

        self.verticalLayout_4.addWidget(self.set_pin_and_show_D_10_P_groupBox)


        self.verticalLayout_3.addWidget(self.set_pin_and_show_frame)

        self.set_pin_and_show_scrollArea.setWidget(self.set_pin_and_show_scrollAreaWidgetContents)
        self.log_display = QFrame(Dialog)
        self.log_display.setObjectName(u"log_display")
        self.log_display.setGeometry(QRect(160, 620, 841, 121))
        self.log_display.setFrameShape(QFrame.StyledPanel)
        self.log_display.setFrameShadow(QFrame.Raised)
        self.log_groupBox = QGroupBox(self.log_display)
        self.log_groupBox.setObjectName(u"log_groupBox")
        self.log_groupBox.setGeometry(QRect(0, 0, 611, 121))
        self.log_data_textBrowser = QTextBrowser(self.log_groupBox)
        self.log_data_textBrowser.setObjectName(u"log_data_textBrowser")
        self.log_data_textBrowser.setGeometry(QRect(10, 20, 591, 81))
        self.log_communication_groupBox = QGroupBox(self.log_display)
        self.log_communication_groupBox.setObjectName(u"log_communication_groupBox")
        self.log_communication_groupBox.setGeometry(QRect(619, 0, 221, 121))
        self.log_reply_textBrowser = QTextBrowser(self.log_communication_groupBox)
        self.log_reply_textBrowser.setObjectName(u"log_reply_textBrowser")
        self.log_reply_textBrowser.setGeometry(QRect(10, 20, 201, 81))
        self.set_paramiter_frame = QFrame(Dialog)
        self.set_paramiter_frame.setObjectName(u"set_paramiter_frame")
        self.set_paramiter_frame.setGeometry(QRect(760, 120, 241, 491))
        self.set_paramiter_frame.setFrameShape(QFrame.StyledPanel)
        self.set_paramiter_frame.setFrameShadow(QFrame.Raised)
        self.Signal_Properties_groupBox = QGroupBox(self.set_paramiter_frame)
        self.Signal_Properties_groupBox.setObjectName(u"Signal_Properties_groupBox")
        self.Signal_Properties_groupBox.setGeometry(QRect(10, 250, 231, 241))
        self.PIN_label = QLabel(self.Signal_Properties_groupBox)
        self.PIN_label.setObjectName(u"PIN_label")
        self.PIN_label.setGeometry(QRect(10, 20, 81, 20))
        self.Signal_Name_lineEdit = QLineEdit(self.Signal_Properties_groupBox)
        self.Signal_Name_lineEdit.setObjectName(u"Signal_Name_lineEdit")
        self.Signal_Name_lineEdit.setGeometry(QRect(90, 50, 131, 22))
        self.Signal_Name_label = QLabel(self.Signal_Properties_groupBox)
        self.Signal_Name_label.setObjectName(u"Signal_Name_label")
        self.Signal_Name_label.setGeometry(QRect(10, 50, 81, 16))
        self.Update_Signal_Properties_pushButton = QPushButton(self.Signal_Properties_groupBox)
        self.Update_Signal_Properties_pushButton.setObjectName(u"Update_Signal_Properties_pushButton")
        self.Update_Signal_Properties_pushButton.setGeometry(QRect(60, 170, 121, 31))
        self.Show_Pin_label = QLabel(self.Signal_Properties_groupBox)
        self.Show_Pin_label.setObjectName(u"Show_Pin_label")
        self.Show_Pin_label.setGeometry(QRect(90, 20, 131, 20))
        self.Signal_Profile_stackedWidget = QStackedWidget(self.Signal_Properties_groupBox)
        self.Signal_Profile_stackedWidget.setObjectName(u"Signal_Profile_stackedWidget")
        self.Signal_Profile_stackedWidget.setGeometry(QRect(10, 80, 221, 51))
        self.Analog_pin_type_page = QWidget()
        self.Analog_pin_type_page.setObjectName(u"Analog_pin_type_page")
        self.Edit_Analog_signal_profile_pushButton = QPushButton(self.Analog_pin_type_page)
        self.Edit_Analog_signal_profile_pushButton.setObjectName(u"Edit_Analog_signal_profile_pushButton")
        self.Edit_Analog_signal_profile_pushButton.setGeometry(QRect(180, 10, 41, 23))
        self.Analog_Signal_Profile_comboBox = QComboBox(self.Analog_pin_type_page)
        self.Analog_Signal_Profile_comboBox.addItem("")
        self.Analog_Signal_Profile_comboBox.addItem("")
        self.Analog_Signal_Profile_comboBox.addItem("")
        self.Analog_Signal_Profile_comboBox.setObjectName(u"Analog_Signal_Profile_comboBox")
        self.Analog_Signal_Profile_comboBox.setGeometry(QRect(80, 11, 91, 21))
        self.Analog_Signal_Profile_label = QLabel(self.Analog_pin_type_page)
        self.Analog_Signal_Profile_label.setObjectName(u"Analog_Signal_Profile_label")
        self.Analog_Signal_Profile_label.setGeometry(QRect(0, 10, 91, 16))
        self.Signal_Profile_stackedWidget.addWidget(self.Analog_pin_type_page)
        self.Digital_pin_type_page = QWidget()
        self.Digital_pin_type_page.setObjectName(u"Digital_pin_type_page")
        self.Digital_Signal_Profile_comboBox = QComboBox(self.Digital_pin_type_page)
        self.Digital_Signal_Profile_comboBox.addItem("")
        self.Digital_Signal_Profile_comboBox.addItem("")
        self.Digital_Signal_Profile_comboBox.setObjectName(u"Digital_Signal_Profile_comboBox")
        self.Digital_Signal_Profile_comboBox.setGeometry(QRect(80, 11, 91, 21))
        self.Digital_Signal_Profile_label = QLabel(self.Digital_pin_type_page)
        self.Digital_Signal_Profile_label.setObjectName(u"Digital_Signal_Profile_label")
        self.Digital_Signal_Profile_label.setGeometry(QRect(0, 10, 91, 16))
        self.Edit_Digital_signal_profile_pushButton = QPushButton(self.Digital_pin_type_page)
        self.Edit_Digital_signal_profile_pushButton.setObjectName(u"Edit_Digital_signal_profile_pushButton")
        self.Edit_Digital_signal_profile_pushButton.setEnabled(False)
        self.Edit_Digital_signal_profile_pushButton.setGeometry(QRect(180, 10, 41, 23))
        self.Signal_Profile_stackedWidget.addWidget(self.Digital_pin_type_page)
        self.Step_groupBox = QGroupBox(self.set_paramiter_frame)
        self.Step_groupBox.setObjectName(u"Step_groupBox")
        self.Step_groupBox.setGeometry(QRect(10, 0, 231, 241))
        self.Update_Step_Block_pushButton = QPushButton(self.Step_groupBox)
        self.Update_Step_Block_pushButton.setObjectName(u"Update_Step_Block_pushButton")
        self.Update_Step_Block_pushButton.setGeometry(QRect(60, 120, 121, 31))
        self.Step_no_label = QLabel(self.Step_groupBox)
        self.Step_no_label.setObjectName(u"Step_no_label")
        self.Step_no_label.setGeometry(QRect(10, 20, 81, 20))
        self.Step_no_comboBox = QComboBox(self.Step_groupBox)
        self.Step_no_comboBox.addItem("")
        self.Step_no_comboBox.addItem("")
        self.Step_no_comboBox.addItem("")
        self.Step_no_comboBox.addItem("")
        self.Step_no_comboBox.addItem("")
        self.Step_no_comboBox.addItem("")
        self.Step_no_comboBox.addItem("")
        self.Step_no_comboBox.addItem("")
        self.Step_no_comboBox.setObjectName(u"Step_no_comboBox")
        self.Step_no_comboBox.setGeometry(QRect(100, 20, 111, 22))
        self.Block_Name_lineEdit = QLineEdit(self.Step_groupBox)
        self.Block_Name_lineEdit.setObjectName(u"Block_Name_lineEdit")
        self.Block_Name_lineEdit.setGeometry(QRect(100, 50, 111, 22))
        self.Block_Name_label = QLabel(self.Step_groupBox)
        self.Block_Name_label.setObjectName(u"Block_Name_label")
        self.Block_Name_label.setGeometry(QRect(10, 50, 81, 20))
        self.Duration_Time_label = QLabel(self.Step_groupBox)
        self.Duration_Time_label.setObjectName(u"Duration_Time_label")
        self.Duration_Time_label.setGeometry(QRect(10, 80, 81, 20))
        self.Duration_Time_lineEdit = QLineEdit(self.Step_groupBox)
        self.Duration_Time_lineEdit.setObjectName(u"Duration_Time_lineEdit")
        self.Duration_Time_lineEdit.setGeometry(QRect(100, 80, 111, 22))
        self.Combine_Signal_pushButton = QPushButton(self.Step_groupBox)
        self.Combine_Signal_pushButton.setObjectName(u"Combine_Signal_pushButton")
        self.Combine_Signal_pushButton.setGeometry(QRect(60, 200, 121, 31))

        self.retranslateUi(Dialog)

        self.Signal_Profile_stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.Connect_board_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Connect Borad", None))
        self.board_host_name_label.setText(QCoreApplication.translate("Dialog", u"Board name/IP:", None))
        self.host_name_comboBox.setEditable(True)
        # self.host_name_comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"Host Name", None))
        self.host_name_comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"rp-f0d457", None))
        self.host_name_comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"192.168.1.100", None))

        self.connect_pushButton.setText(QCoreApplication.translate("Dialog", u"Connect", None))
        self.status_board_label.setText(QCoreApplication.translate("Dialog", u"Status : Disconnected", None))
        self.disconnect_pushButton.setText(QCoreApplication.translate("Dialog", u"Disconnect", None))
        self.poweroff_pushButton.setText(QCoreApplication.translate("Dialog", u"Power OFF", None))
        self.run_pushButton.setText(QCoreApplication.translate("Dialog", u"Run", None))
        self.stop_pushButton.setText(QCoreApplication.translate("Dialog", u"Stop", None))
        self.reset_pushButton.setText(QCoreApplication.translate("Dialog", u"Reset", None))
        self.analog_pin_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Analog", None))
        self.AOUT_0_checkBox.setText(QCoreApplication.translate("Dialog", u"Aout0", None))
        self.AOUT_1_checkBox.setText(QCoreApplication.translate("Dialog", u"Aout1", None))
        self.AOUT_2_checkBox.setText(QCoreApplication.translate("Dialog", u"Aout2", None))
        self.AOUT_3_checkBox.setText(QCoreApplication.translate("Dialog", u"Aout3", None))
        self.digital_pin_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Digital", None))
        self.D_0_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-0-N", None))
        self.D_1_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-1-N", None))
        self.D_2_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-2-N", None))
        self.D_3_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-3-N", None))
        self.D_4_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-4-N", None))
        self.D_5_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-5-N", None))
        self.D_6_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-6-N", None))
        self.D_7_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-7-N", None))
        self.D_8_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-8-N", None))
        self.D_9_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-9-N", None))
        self.D_10_N_checkBox.setText(QCoreApplication.translate("Dialog", u"D-10-N", None))
        self.D_0_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-0-P", None))
        self.D_1_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-1-P", None))
        self.D_2_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-2-P", None))
        self.D_3_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-3-P", None))
        self.D_4_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-4-P", None))
        self.D_5_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-5-P", None))
        self.D_6_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-6-P", None))
        self.D_7_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-7-P", None))
        self.D_8_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-8-P", None))
        self.D_9_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-9-P", None))
        self.D_10_P_checkBox.setText(QCoreApplication.translate("Dialog", u"D-10-P", None))
        self.Add_Digital_Signal_pushButton.setText(QCoreApplication.translate("Dialog", u"Add Digital signal", None))
        self.Add_Analog_Signal_pushButton.setText(QCoreApplication.translate("Dialog", u"Add Analog signal", None))
        self.set_pin_and_show_aout0_groupBox.setTitle("")
        self.AOUT_0_pushButton.setText(QCoreApplication.translate("Dialog", u"Aout0", None))
        self.set_pin_and_show_aout1_groupBox.setTitle("")
        self.AOUT_1_pushButton.setText(QCoreApplication.translate("Dialog", u"Aout1", None))
        self.set_pin_and_show_aout2_groupBox.setTitle("")
        self.AOUT_2_pushButton.setText(QCoreApplication.translate("Dialog", u"Aout2", None))
        self.set_pin_and_show_aout3_groupBox.setTitle("")
        self.AOUT_3_pushButton.setText(QCoreApplication.translate("Dialog", u"Aout3", None))
        self.set_pin_and_show_D_0_N_groupBox.setTitle("")
        self.D_0_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-0-N", None))
        self.set_pin_and_show_D_1_N_groupBox.setTitle("")
        self.D_1_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-1-N", None))
        self.set_pin_and_show_D_2_N_groupBox.setTitle("")
        self.D_2_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-2-N", None))
        self.set_pin_and_show_D_3_N_groupBox.setTitle("")
        self.D_3_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-3-N", None))
        self.set_pin_and_show_D_4_N_groupBox.setTitle("")
        self.D_4_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-4-N", None))
        self.set_pin_and_show_D_5_N_groupBox.setTitle("")
        self.D_5_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-5-N", None))
        self.set_pin_and_show_D_6_N_groupBox.setTitle("")
        self.D_6_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-6-N", None))
        self.set_pin_and_show_D_7_N_groupBox.setTitle("")
        self.D_7_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-7-N", None))
        self.set_pin_and_show_D_8_N_groupBox.setTitle("")
        self.D_8_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-8-N", None))
        self.set_pin_and_show_D_9_N_groupBox.setTitle("")
        self.D_9_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-9-N", None))
        self.set_pin_and_show_D_10_N_groupBox.setTitle("")
        self.D_10_N_pushButton.setText(QCoreApplication.translate("Dialog", u"D-10-N", None))
        self.set_pin_and_show_D_0_P_groupBox.setTitle("")
        self.D_0_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-0-P", None))
        self.set_pin_and_show_D_1_P_groupBox.setTitle("")
        self.D_1_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-1-P", None))
        self.set_pin_and_show_D_2_P_groupBox.setTitle("")
        self.D_2_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-2-P", None))
        self.set_pin_and_show_D_3_P_groupBox.setTitle("")
        self.D_3_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-3-P", None))
        self.set_pin_and_show_D_4_P_groupBox.setTitle("")
        self.D_4_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-4-P", None))
        self.set_pin_and_show_D_5_P_groupBox.setTitle("")
        self.D_5_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-5-P", None))
        self.set_pin_and_show_D_6_P_groupBox.setTitle("")
        self.D_6_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-6-P", None))
        self.set_pin_and_show_D_7_P_groupBox.setTitle("")
        self.D_7_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-7-P", None))
        self.set_pin_and_show_D_8_P_groupBox.setTitle("")
        self.D_8_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-8-P", None))
        self.set_pin_and_show_D_9_P_groupBox.setTitle("")
        self.D_9_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-9-P", None))
        self.set_pin_and_show_D_10_P_groupBox.setTitle("")
        self.D_10_P_pushButton.setText(QCoreApplication.translate("Dialog", u"D-10-P", None))
        self.log_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Log Display", None))
        self.log_communication_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Log  Communication", None))
        self.Signal_Properties_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Signal properties", None))
        self.PIN_label.setText(QCoreApplication.translate("Dialog", u"PIN:", None))
        self.Signal_Name_label.setText(QCoreApplication.translate("Dialog", u"Sinal name:", None))
        self.Update_Signal_Properties_pushButton.setText(QCoreApplication.translate("Dialog", u"Update", None))
        self.Show_Pin_label.setText(QCoreApplication.translate("Dialog", u"TextLabel", None))
        self.Edit_Analog_signal_profile_pushButton.setText(QCoreApplication.translate("Dialog", u"Edit", None))
        self.Analog_Signal_Profile_comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"Constant", None))
        self.Analog_Signal_Profile_comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"Linear_Up", None))
        self.Analog_Signal_Profile_comboBox.setItemText(2, QCoreApplication.translate("Dialog", u"Linear_Down", None))

        self.Analog_Signal_Profile_label.setText(QCoreApplication.translate("Dialog", u"Signal Profile:", None))
        self.Digital_Signal_Profile_comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"Low", None))
        self.Digital_Signal_Profile_comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"High", None))

        self.Digital_Signal_Profile_label.setText(QCoreApplication.translate("Dialog", u"Signal Profile:", None))
        self.Edit_Digital_signal_profile_pushButton.setText(QCoreApplication.translate("Dialog", u"Edit", None))
        self.Step_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Step/Block", None))
        self.Update_Step_Block_pushButton.setText(QCoreApplication.translate("Dialog", u"Update", None))
        self.Step_no_label.setText(QCoreApplication.translate("Dialog", u"Step no.", None))
        self.Step_no_comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"1", None))
        self.Step_no_comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"2", None))
        self.Step_no_comboBox.setItemText(2, QCoreApplication.translate("Dialog", u"3", None))
        self.Step_no_comboBox.setItemText(3, QCoreApplication.translate("Dialog", u"4", None))
        self.Step_no_comboBox.setItemText(4, QCoreApplication.translate("Dialog", u"5", None))
        self.Step_no_comboBox.setItemText(5, QCoreApplication.translate("Dialog", u"6", None))
        self.Step_no_comboBox.setItemText(6, QCoreApplication.translate("Dialog", u"7", None))
        self.Step_no_comboBox.setItemText(7, QCoreApplication.translate("Dialog", u"8", None))

        self.Block_Name_lineEdit.setText("")
        self.Block_Name_label.setText(QCoreApplication.translate("Dialog", u"Block name:", None))
        self.Duration_Time_label.setText(QCoreApplication.translate("Dialog", u"Duration (s):", None))
        self.Duration_Time_lineEdit.setText("")
        self.Combine_Signal_pushButton.setText(QCoreApplication.translate("Dialog", u"combine signal", None))
    # retranslateUi

